// Extended bird sayings for territorial and communicative categories

export const birdTerritorialSayings = [
  "This is MY tree! Everyone else, find your own spot!",
  "I'm defending my territory with pride!",
  "This nesting area belongs to me and my family!",
  "I've claimed this perch and I'm keeping it!",
  "No trespassing in my domain!",
  "I'm the ruler of this branch!",
  "This is my kingdom and I'm the king!",
  "I've established my boundaries and I'm enforcing them!",
  "My territory extends as far as my voice can reach!",
  "I'm protecting my home with fierce determination!",
  "This airspace is under my jurisdiction!",
  "I'm the sovereign of this sky sector!",
  "My domain is sacred and protected!",
  "I've marked this territory as mine!",
  "This is my exclusive flying zone!",
  "I'm the guardian of this aerial realm!",
  "My boundaries are non-negotiable!",
  "This is my personal paradise!",
  "I'm the emperor of this elevation!",
  "My territory is my fortress!",
  "This is my private property!",
  "I'm the lord of this landscape!",
  "My domain extends in all directions!",
  "This is my sovereign state!",
  "I'm the commander of this canopy!",
  "My territory is my birthright!",
  "This is my hereditary homeland!",
  "I'm the chief of this chosen area!",
  "My boundaries define my identity!",
  "This is my ancestral territory!",
  "I'm the duke of this district!",
  "My domain is my destiny!",
  "This is my sacred sanctuary!",
  "I'm the baron of this branch!",
  "My territory is my temple!",
  "This is my holy habitat!",
  "I'm the count of this canopy!",
  "My domain is my cathedral!",
  "This is my blessed boundary!",
  "I'm the earl of this environment!",
  "My territory is my shrine!",
  "This is my divine domain!",
  "I'm the marquis of this meadow!",
  "My boundaries are blessed!",
  "This is my celestial space!",
  "I'm the viscount of this vista!",
  "My territory is my heaven!",
  "This is my ethereal estate!",
  "I'm the prince of this place!",
  "My domain is my paradise!",
  "This is my cosmic corner!",
  "I'm the king of this cosmos!",
  "My territory transcends dimensions!",
  "This is my universal zone!",
  "I'm the emperor of eternity!",
  "My boundaries span infinity!",
  "This is my multidimensional realm!",
  "I'm the god of this galaxy!",
  "My territory is timeless!",
  "This is my quantum quadrant!",
  "I'm the deity of this dimension!",
  "My domain is divine!",
  "This is my spiritual sphere!",
  "I'm the supreme being of this space!",
  "My territory is transcendent!",
  "This is my enlightened environment!",
  "I'm the omnipotent owner!",
  "My boundaries are boundless!",
  "This is my infinite inheritance!",
  "I'm the eternal emperor!",
  "My territory is my truth!",
  "This is my absolute authority!",
  "I'm the limitless lord!",
  "My domain is my divinity!",
  "This is my perfect possession!",
  "I'm the ultimate owner!",
  "My territory is my totality!",
  "This is my complete cosmos!",
  "I'm the final frontier guardian!",
  "My boundaries are my being!",
  "This is my essential existence!",
  "I'm the fundamental force!",
  "My territory is my essence!",
  "This is my core creation!",
  "I'm the primary power!",
  "My domain is my definition!",
  "This is my basic being!",
  "I'm the elemental emperor!",
  "My territory is my molecule!",
  "This is my atomic area!",
  "I'm the quantum king!",
  "My boundaries are my blueprint!",
  "This is my genetic geography!",
  "I'm the DNA deity!",
  "My territory is my code!",
  "This is my programmed place!",
  "I'm the algorithmic authority!",
  "My domain is my data!",
  "This is my digital dimension!",
  "I'm the binary baron!",
  "My territory is my technology!",
  "This is my virtual vista!",
  "I'm the cyber sovereign!",
  "My boundaries are my bandwidth!",
  "This is my networked nature!",
  "I'm the internet emperor!",
  "My territory is my matrix!"
];

export const birdCommunicativeSayings = [
  "I'm calling to my mate across the forest!",
  "Listen to my beautiful song!",
  "I'm sharing the news of the day with my flock!",
  "My voice carries messages of love and warning!",
  "I'm announcing my presence to the world!",
  "My melody tells the story of my heart!",
  "I'm broadcasting important information!",
  "My song is a bridge between souls!",
  "I'm weaving words into the wind!",
  "My voice is my gift to the universe!",
  "I'm painting pictures with sound!",
  "My melody is my signature!",
  "I'm composing symphonies of the sky!",
  "My song is my spiritual expression!",
  "I'm channeling the music of nature!",
  "My voice is my connection to all!",
  "I'm singing the language of love!",
  "My melody is my meditation!",
  "I'm harmonizing with the cosmos!",
  "My song is my prayer!",
  "I'm vocalizing my deepest emotions!",
  "My voice is my vessel of truth!",
  "I'm broadcasting my soul's frequency!",
  "My melody is my message!",
  "I'm singing the songs of my ancestors!",
  "My voice carries ancient wisdom!",
  "I'm channeling the choir of creation!",
  "My song is my sacred offering!",
  "I'm vocalizing the voice of the divine!",
  "My melody is my manifestation!",
  "I'm singing the secrets of the universe!",
  "My voice is my vibrational signature!",
  "I'm broadcasting on the frequency of love!",
  "My song is my sonic sculpture!",
  "I'm painting rainbows with my voice!",
  "My melody is my magical incantation!",
  "I'm singing spells of pure beauty!",
  "My voice is my wand of wonder!",
  "I'm casting charms with my chorus!",
  "My song is my spell of serenity!",
  "I'm enchanting the world with melody!",
  "My voice is my vessel of virtue!",
  "I'm broadcasting blessings through song!",
  "My melody is my miracle!",
  "I'm singing salvation to all souls!",
  "My voice is my vehicle of victory!",
  "I'm proclaiming peace through song!",
  "My melody is my ministry!",
  "I'm evangelizing through euphony!",
  "My voice is my vessel of virtue!",
  "I'm preaching through pure sound!",
  "My song is my sermon!",
  "I'm testifying through my tune!",
  "My voice is my witness!",
  "I'm prophesying through my performance!",
  "My melody is my mission!",
  "I'm spreading the gospel of joy!",
  "My voice is my revelation!",
  "I'm declaring divine truths!",
  "My song is my scripture!",
  "I'm reciting the word of wonder!",
  "My voice is my verse!",
  "I'm chanting the chorus of creation!",
  "My melody is my mantra!",
  "I'm intoning the infinite!",
  "My voice is my vibration!",
  "I'm resonating with reality!",
  "My song is my frequency!",
  "I'm oscillating with the universe!",
  "My voice is my wave!",
  "I'm surfing the sonic spectrum!",
  "My melody is my motion!",
  "I'm dancing through dimensions!",
  "My voice is my velocity!",
  "I'm traveling at the speed of sound!",
  "My song is my spaceship!",
  "I'm journeying through the cosmos!",
  "My voice is my vehicle!",
  "I'm navigating the sonic seas!",
  "My melody is my map!",
  "I'm charting courses through consciousness!",
  "My voice is my compass!",
  "I'm exploring the edges of existence!",
  "My song is my satellite!",
  "I'm transmitting to distant dimensions!",
  "My voice is my signal!",
  "I'm communicating across the cosmos!",
  "My melody is my message!",
  "I'm broadcasting to the universe!",
  "My voice is my beacon!",
  "I'm guiding souls through sound!",
  "My song is my lighthouse!",
  "I'm illuminating the path with melody!",
  "My voice is my torch!",
  "I'm lighting the way with song!",
  "My melody is my flame!",
  "I'm burning bright with beautiful sound!",
  "My voice is my fire!",
  "I'm igniting inspiration everywhere!",
  "My song is my spark!",
  "I'm kindling creativity in all!",
  "My voice is my energy!",
  "I'm powering the world with song!",
  "My melody is my electricity!",
  "I'm charging the atmosphere with joy!",
  "My voice is my voltage!",
  "I'm electrifying existence with song!"
];