// Extended cat sayings for demanding and content categories

export const catDemandingSayings = [
  "Human! I require your immediate attention for my needs!",
  "My food bowl is unacceptably empty!",
  "I demand to be fed this instant!",
  "Open this door for me right now!",
  "I need fresh water and I need it now!",
  "Pet me immediately or face the consequences!",
  "My litter box requires your attention!",
  "I'm hungry and I'm not being subtle about it!",
  "Serve me like the royalty I am!",
  "I have needs and you will fulfill them!",
  "Your service is required immediately!",
  "I command you to attend to me!",
  "My royal decree demands compliance!",
  "You exist solely to serve my needs!",
  "I am the emperor and you are my servant!",
  "My wishes are not suggestions, they're orders!",
  "I require immediate gratification!",
  "Your attention is mandatory, not optional!",
  "I am the supreme ruler of this domain!",
  "My demands supersede all other priorities!",
  "You will cater to my every whim!",
  "I expect instant obedience to my commands!",
  "My needs are the center of the universe!",
  "I am the dictator of this household!",
  "Your sole purpose is my satisfaction!",
  "I require worship and adoration!",
  "My comfort is your primary responsibility!",
  "I am the CEO of this establishment!",
  "Your job is to anticipate my desires!",
  "I demand five-star treatment!",
  "My satisfaction is non-negotiable!",
  "I am the monarch of this castle!",
  "Your devotion must be absolute!",
  "I require premium service immediately!",
  "My happiness is your only concern!",
  "I am the overlord of this territory!",
  "Your compliance is not optional!",
  "I demand luxury accommodations!",
  "My pleasure is your obligation!",
  "I am the supreme commander here!",
  "Your submission is expected!",
  "I require royal treatment!",
  "My contentment is your mission!",
  "I am the pharaoh of this pyramid!",
  "Your servitude is appreciated!",
  "I demand imperial service!",
  "My bliss is your responsibility!",
  "I am the kaiser of this kingdom!",
  "Your dedication must be unwavering!",
  "I require aristocratic attention!",
  "My euphoria is your goal!",
  "I am the czar of this realm!",
  "Your loyalty is mandatory!",
  "I demand noble treatment!",
  "My ecstasy is your purpose!",
  "I am the sultan of this palace!",
  "Your reverence is required!",
  "I require majestic service!",
  "My rapture is your duty!",
  "I am the shah of this sanctuary!",
  "Your homage is expected!",
  "I demand regal attention!",
  "My nirvana is your calling!",
  "I am the maharaja of this mansion!",
  "Your tribute is necessary!",
  "I require sovereign service!",
  "My paradise is your mission!",
  "I am the emperor of this empire!",
  "Your worship is obligatory!",
  "I demand divine treatment!",
  "My heaven is your responsibility!",
  "I am the god of this temple!",
  "Your prayers are required!",
  "I require celestial service!",
  "My enlightenment is your goal!",
  "I am the deity of this shrine!",
  "Your offerings are expected!",
  "I demand cosmic attention!",
  "My transcendence is your purpose!",
  "I am the universe's center!",
  "Your devotion spans dimensions!",
  "I require infinite service!",
  "My omnipotence is your reality!",
  "I am the alpha and omega!",
  "Your existence serves my glory!",
  "I demand eternal worship!",
  "My supremacy is absolute!",
  "I am the beginning and end!",
  "Your purpose is my pleasure!",
  "I require boundless devotion!",
  "My dominion is limitless!",
  "I am the source of all!",
  "Your life revolves around me!",
  "I demand perpetual service!",
  "My reign is everlasting!",
  "I am the essence of power!",
  "Your soul belongs to me!",
  "I require unconditional surrender!",
  "My authority is unquestionable!",
  "I am the master of reality!",
  "Your spirit serves my will!",
  "I demand total submission!",
  "My control is complete!",
  "I am the ruler of existence!",
  "Your consciousness bows to me!",
  "I require absolute obedience!",
  "My power is infinite!"
];

export const catContentSayings = [
  "I'm perfectly comfortable right here, thank you.",
  "This sunny spot is exactly where I belong.",
  "Life is good when you're this relaxed.",
  "I've found the perfect napping position.",
  "Everything is as it should be in my kingdom.",
  "This moment of tranquility is divine.",
  "I'm in my element of pure serenity.",
  "Peace flows through my very being.",
  "This is what true contentment feels like.",
  "I'm one with the universe right now.",
  "My soul is perfectly aligned.",
  "This warmth penetrates to my core.",
  "I'm experiencing pure bliss.",
  "My spirit is completely at ease.",
  "This comfort is absolutely perfect.",
  "I'm floating on clouds of satisfaction.",
  "My heart is filled with calm joy.",
  "This peace is deeply nourishing.",
  "I'm basking in pure happiness.",
  "My being radiates contentment.",
  "This moment is absolutely sacred.",
  "I'm swimming in an ocean of calm.",
  "My essence is pure tranquility.",
  "This serenity is my natural state.",
  "I'm glowing with inner peace.",
  "My soul is perfectly still.",
  "This comfort transcends description.",
  "I'm melting into pure relaxation.",
  "My spirit is completely fulfilled.",
  "This warmth is healing my soul.",
  "I'm vibrating at the frequency of peace.",
  "My heart is overflowing with calm.",
  "This moment is pure meditation.",
  "I'm dissolving into perfect rest.",
  "My being is completely harmonized.",
  "This comfort is absolutely divine.",
  "I'm floating in liquid serenity.",
  "My essence is pure satisfaction.",
  "This peace is my sanctuary.",
  "I'm glowing with contentment.",
  "My soul is perfectly balanced.",
  "This tranquility is my home.",
  "I'm swimming in pure comfort.",
  "My spirit is completely centered.",
  "This moment is my paradise.",
  "I'm radiating peaceful energy.",
  "My heart is perfectly calm.",
  "This serenity is my temple.",
  "I'm melting into pure bliss.",
  "My being is completely relaxed.",
  "This comfort is my universe.",
  "I'm floating on waves of peace.",
  "My essence is pure harmony.",
  "This tranquility is my reality.",
  "I'm glowing with inner light.",
  "My soul is perfectly content.",
  "This moment is my meditation.",
  "I'm dissolving into pure joy.",
  "My spirit is completely free.",
  "This peace is my foundation.",
  "I'm swimming in golden calm.",
  "My heart is perfectly still.",
  "This serenity is my essence.",
  "I'm floating in pure love.",
  "My being is completely whole.",
  "This comfort is my truth.",
  "I'm radiating divine peace.",
  "My soul is perfectly aligned.",
  "This tranquility is my nature.",
  "I'm melting into cosmic calm.",
  "My spirit is completely pure.",
  "This moment is my eternity.",
  "I'm glowing with universal love.",
  "My heart is perfectly open.",
  "This serenity is my infinity.",
  "I'm floating in quantum peace.",
  "My essence is pure consciousness.",
  "This comfort is my dimension.",
  "I'm swimming in liquid light.",
  "My being is completely enlightened.",
  "This peace is my frequency.",
  "I'm radiating cosmic energy.",
  "My soul is perfectly expanded.",
  "This tranquility is my vibration.",
  "I'm melting into pure awareness.",
  "My spirit is completely awakened.",
  "This moment is my transcendence.",
  "I'm glowing with divine essence.",
  "My heart is perfectly unified.",
  "This serenity is my evolution.",
  "I'm floating in pure potential.",
  "My being is completely realized.",
  "This comfort is my manifestation.",
  "I'm swimming in infinite wisdom.",
  "My essence is pure creation.",
  "This peace is my expression.",
  "I'm radiating boundless love.",
  "My soul is perfectly expanded.",
  "This tranquility is my gift.",
  "I'm melting into pure source.",
  "My spirit is completely connected.",
  "This moment is my revelation.",
  "I'm glowing with eternal light.",
  "My heart is perfectly integrated."
];