// Extended dog sayings for alert and protective categories

export const dogAlertSayings = [
  "Hey! Something's happening over there! Should I be concerned?",
  "Did you hear that noise? I'm on high alert!",
  "There's someone at the door! I must investigate!",
  "My senses are telling me something's different!",
  "I'm keeping watch over our territory!",
  "Something doesn't smell right around here!",
  "I hear footsteps! Everyone be ready!",
  "My ears are picking up unusual sounds!",
  "There's movement in the bushes!",
  "I'm your early warning system!",
  "My radar is detecting anomalies!",
  "All systems are on high alert!",
  "I'm scanning the perimeter for threats!",
  "My sensors are picking up disturbances!",
  "Vigilance is my middle name!",
  "I'm monitoring all frequencies!",
  "My detection systems are active!",
  "I'm your security specialist!",
  "Threat assessment in progress!",
  "My awareness levels are maxed out!",
  "I'm your personal surveillance system!",
  "My instincts are firing on all cylinders!",
  "I'm your neighborhood watch captain!",
  "My senses are operating at peak efficiency!",
  "I'm your early detection specialist!",
  "My alert systems are fully operational!",
  "I'm your guardian angel with fur!",
  "My protective protocols are engaged!",
  "I'm your living security camera!",
  "My danger sensors are calibrated perfectly!",
  "I'm your personal bodyguard!",
  "My threat detection is second to none!",
  "I'm your home security system!",
  "My vigilance never wavers!",
  "I'm your four-legged alarm system!",
  "My awareness spans 360 degrees!",
  "I'm your faithful sentinel!",
  "My detection range is impressive!",
  "I'm your loyal watchdog!",
  "My senses are finely tuned instruments!",
  "I'm your personal security detail!",
  "My alert level is always optimal!",
  "I'm your dedicated protector!",
  "My surveillance capabilities are unmatched!",
  "I'm your trusty guard!",
  "My detection skills are legendary!",
  "I'm your reliable lookout!",
  "My senses are my superpowers!",
  "I'm your personal security force!",
  "My vigilance is unwavering!",
  "I'm your mobile defense unit!",
  "My awareness is my greatest asset!",
  "I'm your faithful guardian!",
  "My detection abilities are extraordinary!",
  "I'm your personal safety net!",
  "My senses are always on duty!",
  "I'm your dedicated watchman!",
  "My alert systems never sleep!",
  "I'm your protective companion!",
  "My surveillance is comprehensive!",
  "I'm your security consultant!",
  "My detection network is vast!",
  "I'm your personal shield!",
  "My senses are my radar!",
  "I'm your loyal defender!",
  "My vigilance is my calling!",
  "I'm your security specialist!",
  "My awareness is my strength!",
  "I'm your protective barrier!",
  "My detection is instantaneous!",
  "I'm your guardian spirit!",
  "My senses are my weapons!",
  "I'm your security blanket!",
  "My vigilance is absolute!",
  "I'm your protective force field!",
  "My detection is flawless!",
  "I'm your security fortress!",
  "My senses are my armor!",
  "I'm your protective shield!",
  "My vigilance is eternal!",
  "I'm your security sanctuary!",
  "My detection is infallible!",
  "I'm your protective dome!",
  "My senses are my fortress!",
  "I'm your security haven!",
  "My vigilance is infinite!",
  "I'm your protective bubble!",
  "My detection is omnipresent!",
  "I'm your security cocoon!",
  "My senses are my castle!",
  "I'm your protective aura!",
  "My vigilance is omniscient!",
  "I'm your security matrix!",
  "My detection is all-seeing!",
  "I'm your protective energy!",
  "My senses are my universe!",
  "I'm your security dimension!",
  "My vigilance is multidimensional!",
  "I'm your protective reality!",
  "My detection transcends space!",
  "I'm your security cosmos!"
];

export const dogProtectiveSayings = [
  "I'm guarding my family with my life!",
  "Nobody gets past me without permission!",
  "This is my pack and I'll defend them!",
  "I'm standing between danger and my loved ones!",
  "My protective instincts are in full force!",
  "I'm your shield against all threats!",
  "My loyalty runs deeper than blood!",
  "I'll fight to my last breath for you!",
  "My protective spirit is unbreakable!",
  "I'm your fortress of safety!",
  "My devotion knows no limits!",
  "I'm your guardian warrior!",
  "My protective love is fierce!",
  "I'm your living armor!",
  "My courage is boundless for you!",
  "I'm your fearless protector!",
  "My protective bond is sacred!",
  "I'm your shield of honor!",
  "My defensive instincts are primal!",
  "I'm your wall of protection!",
  "My protective nature is divine!",
  "I'm your guardian angel!",
  "My loyalty is my superpower!",
  "I'm your protective force!",
  "My devotion is unwavering!",
  "I'm your safety net!",
  "My protective heart beats for you!",
  "I'm your living shield!",
  "My courage multiplies for family!",
  "I'm your protective sanctuary!",
  "My loyalty is my religion!",
  "I'm your guardian fortress!",
  "My protective soul is pure!",
  "I'm your safety guardian!",
  "My devotion is absolute!",
  "I'm your protective barrier!",
  "My loyalty transcends fear!",
  "I'm your guardian spirit!",
  "My protective essence is strong!",
  "I'm your safety shield!",
  "My devotion is infinite!",
  "I'm your protective aura!",
  "My loyalty is eternal!",
  "I'm your guardian energy!",
  "My protective power is limitless!",
  "I'm your safety force!",
  "My devotion is cosmic!",
  "I'm your protective universe!",
  "My loyalty is transcendent!",
  "I'm your guardian dimension!",
  "My protective essence is divine!",
  "I'm your safety cosmos!",
  "My devotion is multidimensional!",
  "I'm your protective infinity!",
  "My loyalty is omnipresent!",
  "I'm your guardian eternity!",
  "My protective spirit is boundless!",
  "I'm your safety reality!",
  "My devotion is all-encompassing!",
  "I'm your protective existence!",
  "My loyalty is universal!",
  "I'm your guardian consciousness!",
  "My protective energy is pure!",
  "I'm your safety essence!",
  "My devotion is primordial!",
  "I'm your protective soul!",
  "My loyalty is fundamental!",
  "I'm your guardian core!",
  "My protective nature is eternal!",
  "I'm your safety foundation!",
  "My devotion is elemental!",
  "I'm your protective element!",
  "My loyalty is molecular!",
  "I'm your guardian atom!",
  "My protective force is quantum!",
  "I'm your safety particle!",
  "My devotion is subatomic!",
  "I'm your protective wave!",
  "My loyalty is electromagnetic!",
  "I'm your guardian frequency!",
  "My protective vibration is pure!",
  "I'm your safety resonance!",
  "My devotion is harmonic!",
  "I'm your protective symphony!",
  "My loyalty is melodic!",
  "I'm your guardian rhythm!",
  "My protective beat is strong!",
  "I'm your safety tempo!",
  "My devotion is musical!",
  "I'm your protective song!",
  "My loyalty is lyrical!",
  "I'm your guardian verse!",
  "My protective chorus is loud!",
  "I'm your safety harmony!",
  "My devotion is orchestral!",
  "I'm your protective composition!",
  "My loyalty is artistic!",
  "I'm your guardian masterpiece!",
  "My protective creation is beautiful!",
  "I'm your safety inspiration!",
  "My devotion is poetic!",
  "I'm your protective verse!"
];