// Enhanced sayings database part 3 - Bird, Crow, and other animals

export const enhancedBirdSayings = {
  territorial: [
    "This airspace belongs to me and my lineage!",
    "I claim dominion over this entire territory!",
    "My boundaries are clearly established and defended!",
    "This domain is under my sovereign protection!",
    "I am the undisputed ruler of this aerial kingdom!",
    "My territory extends as far as my voice carries!",
    "This space is mine by right of first claim!",
    "I establish my borders with unwavering authority!",
    "My domain is sacred and will be protected!",
    "This territory is my ancestral inheritance!",
    "I mark my boundaries with vocal precision!",
    "My realm is defended with fierce determination!",
    "This airspace is under my exclusive jurisdiction!",
    "I proclaim ownership of this entire area!",
    "My territory is my castle in the sky!",
    "This domain reflects my superior status!",
    "I defend my borders with aerial superiority!",
    "My space is clearly marked and protected!",
    "This territory is my personal empire!",
    "I rule this airspace with absolute authority!",
    "My domain is established through vocal power!",
    "This territory is my sovereign nation!",
    "I claim this space through rightful conquest!",
    "My boundaries are enforced without compromise!",
    "This airspace is my hereditary kingdom!"
  ],
  communicative: [
    "Let's create beautiful melodies together as one!",
    "Our voices unite in perfect harmonic symphony!",
    "I'm sharing the joy of community connection!",
    "Together we form an incredible aerial chorus!",
    "Our songs weave the fabric of social bonding!",
    "I'm contributing to our collective musical story!",
    "We're creating acoustic art through collaboration!",
    "Our voices blend in magnificent cooperation!",
    "I'm expressing the beauty of flock unity!",
    "Together we compose nature's greatest symphony!",
    "Our communication strengthens community bonds!",
    "I'm sharing wisdom through melodic expression!",
    "We're building bridges through vocal harmony!",
    "Our songs celebrate the power of togetherness!",
    "I'm contributing my voice to our shared narrative!",
    "Together we create music that transcends words!",
    "Our communication is poetry in motion!",
    "I'm expressing the joy of social connection!",
    "We're weaving melodies of mutual understanding!",
    "Our voices unite in celebration of community!",
    "I'm sharing the gift of harmonious expression!",
    "Together we create acoustic masterpieces!",
    "Our communication builds lasting relationships!",
    "I'm contributing to our collective voice!",
    "We're creating symphonies of social harmony!"
  ]
};