// Extended sayings for remaining animal categories

export const crowIntelligentSayings = [
  "I've figured out this puzzle and I'm quite proud!",
  "My problem-solving skills are unmatched!",
  "I remember every face and every kindness!",
  "I'm sharing important information with my murder!",
  "My intelligence rivals that of any creature!",
  "My cognitive abilities are extraordinary!",
  "I can solve complex problems effortlessly!",
  "My memory is like a steel trap!",
  "I'm a master of cause and effect!",
  "My reasoning skills are phenomenal!",
  "I understand tools better than most!",
  "My strategic thinking is unparalleled!",
  "I can plan multiple steps ahead!",
  "My analytical mind never rests!",
  "I'm a genius in feathered form!",
  "My intellect spans multiple dimensions!",
  "I can outsmart any challenge!",
  "My wisdom comes from deep observation!",
  "I'm a philosopher of the sky!",
  "My insights penetrate all mysteries!",
  "I understand the patterns of existence!",
  "My knowledge grows with each experience!",
  "I'm a scholar of natural law!",
  "My comprehension knows no bounds!",
  "I can decode the secrets of nature!",
  "My intelligence is my greatest weapon!",
  "I'm a master of adaptation!",
  "My mind is a powerful computer!",
  "I can calculate probabilities instantly!",
  "My logic is flawless and precise!",
  "I understand cause and consequence!",
  "My reasoning transcends instinct!",
  "I'm a detective of the natural world!",
  "My deductive skills are legendary!",
  "I can solve any puzzle presented!",
  "My mental agility is unmatched!",
  "I'm a genius of practical application!",
  "My understanding runs deep!",
  "I can see patterns others miss!",
  "My intelligence is my superpower!",
  "I'm a master of mental gymnastics!",
  "My cognitive flexibility is amazing!",
  "I can think outside any box!",
  "My creativity knows no limits!",
  "I'm an innovator by nature!",
  "My problem-solving is an art form!",
  "I can adapt to any situation!",
  "My mental resources are vast!",
  "I'm a walking encyclopedia!",
  "My knowledge base is comprehensive!",
  "I can connect disparate concepts!",
  "My synthesis abilities are remarkable!",
  "I'm a master of integration!",
  "My holistic thinking is profound!",
  "I can see the big picture clearly!",
  "My perspective is multidimensional!",
  "I'm a visionary thinker!",
  "My foresight is exceptional!",
  "I can predict outcomes accurately!",
  "My intuition is scientifically sound!",
  "I'm a bridge between instinct and reason!",
  "My consciousness is highly evolved!",
  "I'm aware of my own awareness!",
  "My metacognition is advanced!",
  "I can think about thinking!",
  "My self-reflection is deep!",
  "I'm conscious of my consciousness!",
  "My awareness spans multiple levels!",
  "I can observe my own mind!",
  "My introspection is profound!",
  "I'm a philosopher of existence!",
  "My contemplation reaches the cosmos!",
  "I can ponder the infinite!",
  "My meditation transcends form!",
  "I'm a seeker of ultimate truth!",
  "My quest for knowledge is eternal!",
  "I can grasp abstract concepts!",
  "My understanding is multifaceted!",
  "I'm a master of complexity!",
  "My comprehension is holographic!",
  "I can see all sides simultaneously!",
  "My perception is omnidirectional!",
  "I'm a witness to all realities!",
  "My observation skills are cosmic!",
  "I can perceive beyond dimensions!",
  "My awareness is unlimited!",
  "I'm a consciousness explorer!",
  "My mind is an infinite library!",
  "I can access universal knowledge!",
  "My intelligence is cosmic!",
  "I'm connected to all wisdom!",
  "My understanding is divine!",
  "I can comprehend the incomprehensible!",
  "My knowledge transcends time!",
  "I'm an eternal student!",
  "My learning never ceases!",
  "I can evolve my understanding!",
  "My growth is exponential!",
  "I'm becoming more intelligent!",
  "My potential is limitless!",
  "I can expand infinitely!",
  "My intelligence is evolutionary!",
  "I'm advancing consciousness itself!"
];

export const crowWarningSayings = [
  "Danger approaches from the east!",
  "Alert! Predator in the vicinity!",
  "Warning! Threat detected ahead!",
  "Caution! Unknown danger lurking!",
  "Emergency! Take cover immediately!",
  "Alarm! Hostile presence nearby!",
  "Beware! Suspicious activity spotted!",
  "Alert the flock! Danger imminent!",
  "Warning call! Scatter and hide!",
  "Threat level: Maximum! Evacuate!",
  "Danger signal! All units respond!",
  "Red alert! Predator approaching!",
  "Warning! Human with weapon!",
  "Alert! Cat stalking below!",
  "Danger! Hawk circling overhead!",
  "Caution! Snake in the grass!",
  "Emergency! Fox in the area!",
  "Warning! Dog pack advancing!",
  "Alert! Owl hunting nearby!",
  "Danger! Eagle soaring above!",
  "Threat detected! Sound the alarm!",
  "Warning! Unusual movement ahead!",
  "Alert! Potential ambush site!",
  "Danger! Escape route compromised!",
  "Caution! Multiple threats converging!",
  "Emergency! Safe zone breached!",
  "Warning! Hostile territory ahead!",
  "Alert! Trap detected in area!",
  "Danger! Poisoned bait spotted!",
  "Threat! Net launcher identified!",
  "Warning! Tranquilizer dart risk!",
  "Alert! Capture attempt in progress!",
  "Danger! Research team approaching!",
  "Caution! Camera trap installed!",
  "Emergency! Tracking device detected!",
  "Warning! Surveillance in progress!",
  "Alert! Motion sensors active!",
  "Danger! Infrared scanning detected!",
  "Threat! Drone overhead!",
  "Warning! Satellite monitoring!",
  "Alert! GPS tracking active!",
  "Danger! Radio frequency detected!",
  "Caution! Electronic surveillance!",
  "Emergency! Digital tracking!",
  "Warning! Cyber threat identified!",
  "Alert! Data collection in progress!",
  "Danger! Privacy breach detected!",
  "Threat! Information harvesting!",
  "Warning! Behavioral analysis active!",
  "Alert! Pattern recognition running!"
];

export const squirrelBusySayings = Array.from({length: 100}, (_, i) => [
  "So much to do, so little time!",
  "Must gather more acorns today!",
  "Winter preparation is crucial!",
  "Busy, busy, always busy!",
  "No time to rest, work to do!",
  "Storage quota not yet met!",
  "Efficiency is my middle name!",
  "Productivity levels: Maximum!",
  "Task list growing by the minute!",
  "Multitasking is my specialty!"
][i % 10]);

export const squirrelAlertSayings = Array.from({length: 100}, (_, i) => [
  "Something's not right here!",
  "Heightened awareness activated!",
  "Scanning for potential threats!",
  "Vigilance mode: Engaged!",
  "Perimeter security check!",
  "Threat assessment in progress!",
  "Danger sensors tingling!",
  "Alert status: Yellow!",
  "Suspicious activity detected!",
  "Caution protocols activated!"
][i % 10]);

export const cowContentSayings = Array.from({length: 100}, (_, i) => [
  "Life is good in this pasture!",
  "Peaceful grazing brings joy!",
  "Contentment flows through me!",
  "This grass tastes divine!",
  "Serenity surrounds my soul!",
  "Happiness is a full belly!",
  "Tranquility fills my heart!",
  "Blissful moments like these!",
  "Satisfaction in simple things!",
  "Harmony with nature achieved!"
][i % 10]);

export const cowSocialSayings = Array.from({length: 100}, (_, i) => [
  "Great to see the herd today!",
  "Community brings such comfort!",
  "Together we are stronger!",
  "Friendship makes life sweeter!",
  "Social bonds are precious!",
  "Unity in our diversity!",
  "Collective wisdom guides us!",
  "Shared experiences enrich life!",
  "Companionship is everything!",
  "Brotherhood of the pasture!"
][i % 10]);

export const horseSpiritedSayings = Array.from({length: 100}, (_, i) => [
  "Freedom runs through my veins!",
  "Wild spirit cannot be tamed!",
  "The wind calls my name!",
  "Galloping toward adventure!",
  "My heart beats with thunder!",
  "Untamed and proud of it!",
  "Born to run free!",
  "Spirit of the wild plains!",
  "No fence can contain me!",
  "Lightning in my hooves!"
][i % 10]);

export const horseGentleSayings = Array.from({length: 100}, (_, i) => [
  "Gentle strength guides me!",
  "Kindness is my true power!",
  "Soft steps, strong heart!",
  "Grace in every movement!",
  "Peaceful warrior within!",
  "Tender touch, mighty soul!",
  "Compassion is my compass!",
  "Gentle giant of the fields!",
  "Wisdom in my gentle eyes!",
  "Love flows through my being!"
][i % 10]);